image: node:latest
stages: 
  - build         # List of stages for jobs, and their order of execution
  - test
variables:
  CYPRESS_RECORD_KEY: $CYPRESS_RECORD_KEY

clear-report:
  stage: build
  script:
    - echo "Clear the report"
    - npm run delete-mochawesome-report
    - npm run delete-results

run-tests:  
  stage: test  
  image: cypress/browsers:node16.16.0-chrome107-ff107
  parallel: 2 #Uses two parallel instances
  before_script: 
    - echo "Installing TypeScript"
    - npm install typescript
  script:
    - echo "Starting all tests headless and creating report with screenshots"
    - npm run triggerAllTests-headless
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - cypress/reports/*
    