name: Run All Tests Headless

on:
    workflow_dispatch:
      inputs:
        ru:
          description: The variable to be passed
          required: false
          default: TEST
    schedule:
        - cron: 0 7 * * 1

jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
              containers: [1, 2] # Uses 2 parallel instances
        container:
          image: cypress/browser:latest #latest Cypress Chrome docker image
          options: --user 1001 #all permisions
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                node-version: 18.14.2

            - name: Update & Install Ubuntu packages
              run: |
                env
                sudo apt-get update && sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

            - name: Update & Install NPM packages
              run: |
                npx browserslist@latest --update-db
                npm ci

            - name: Clear Report
              run: |
                echo "Clear the report"
                npm run delete-mochawesome-report
                npm run delete-results

            - name: Run Tests
              uses: cypress-io/github-action@v6
              with:
                record: true
                parallel: true
                browser: chrome
                group: 'e2e-tests'
                spec: 'cypress/e2e/automation-test-store/*'
              env:
                CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                RU: ${{ github.event.inputs.ru || 'TEST' }}
                # CYPRESS_BASE_URL: ''
  
            - name: Prepare report
              if: success() || failure()
              run: |
                mkdir -p cypress/results/
                cp -r cypress/reports/html/* cypress/results/

            - name: Archive results
              if: success() || failure()
              uses: actions/upload-artifact@v3
              with:
                name: artifacts
                path: |
                  cypress/results/**

